---
    php_ppa: php5-5.6
    doc_root: /vagrant
    sys_packages: ["vim", "redis-server", "python", "python-setuptools", "python-pip", "python-dev", "libxslt1-dev", "libxml2-dev", "libz-dev", "libffi-dev", "libssl-dev"]
    dist: precise
    php_packages: ["php5-pgsql"]
