sentry:
    virtualenv: /www/sentry/
    template: sentry.conf.py
    admin_email: admin@sentry.server
    admin_password: admin
    hostname: sentry.server
    server_email: sentry@sentry.server
    secret: VDpBG3DQOapXLkDqQDt8ToJd4ty6/1GOvpTHUO4o0sHtDIMAIKzxZQ==
    port: 9000
    mailgun_key: ''
    extensions: [ "sentry-github", "sentry-slack" ]
    twitter_consumer_key: ''
    twitter_consumer_secret: ''
    facebook_app_id: ''
    facebook_api_secret: ''
    google_oauth2_client_id: ''
    google_oauth2_client_secret: ''
    github_app_id: ''
    github_api_secret: ''
    trello_api_key: ''
    trello_api_secret: ''
    bitbucket_consumer_key: ''
    bitbucket_consumer_secret: ''