---

- name: Add PostgreSQL Repository
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main' state=present

- name: Add Keys for PostgreSQL Repository
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: Update apt
  apt: update_cache=yes

- name: Install PostgreSQL Packages
  apt: pkg={{ item }} state=latest
  with_items:
    - postgresql-9.4
    - postgresql-client-9.4
    - python-pygresql
    - python-psycopg2
    - postgresql-server-dev-9.4

- name: Create databases
  remote_user: root
  become: yes
  become_user: postgres
  postgresql_db: 
    name: '{{ pgsql.database }}'
    state: present

- name: Create users
  remote_user: root
  become: yes
  become_user: postgres
  postgresql_user: 
    name: '{{ pgsql.user }}' 
    password: '{{ pgsql.password }}'
    db: '{{ pgsql.database }}'
    priv: ALL
    role_attr_flags: SUPERUSER

- name: Set authentication config
  template: src={{ pgsql.auth_template }} dest=/etc/postgresql/9.4/main/pg_hba.conf
  notify: Restart postgres

- name: Restart postgres immediately
  service: name=postgresql enabled=yes state=restarted
