---
- hosts: all
  sudo: true
  vars:
    web_server: nginx
    servername: sentry.server 192.168.33.89
    timezone: Europe/Brussels
  vars_files:
    - vars/pgsql.yml
    - vars/sentry.yml
    - vars/supervisor.yml
    - vars/common.yml
    - vars/nginx.yml
  roles:
    - init
    - nginx
    - pgsql
    - sentry
    - supervisor
    - app
